[User Manual] Added example when less than 16cells are used.
LibreSolar/bms-c1 pull request #62
Opened 2024-06-11 17:36 UTC by jalinei

- Added a different color for BMS power signals (first and last wires of the harness) 
- Added a connection example for a 12s battery so that it is easier to understand how to wire the harness.
- Added a zoom view to explain what "exposed pads" refers to.

2024-06-11 20:34 UTC, martinjaeger requested changes
Thanks @jalinei, that's a very nice improvement.

Only got a small remark to make sure the markdown is rendered correctly also for the PDF. (unfortunately, this is not yet generated in CI for PRs)

2024-06-11 20:34 UTC, martinjaeger commented on manual/4-installation.md
> +  - or in the wiring harness directly.
We need some more spaces here in order to render the markdown correctly, otherwise it looks like this:
![image](https://github.com/LibreSolar/bms-c1/assets/17674105/e7cca136-0127-4903-aadc-485132bd8dfd)

```suggestion
The first signal connection and the very last one (respectively shown in grey and orange in the connection diagram) are used for powering up the BMS.

If less than 16 cells are used:

- Route the last wire of the harness (shown in orange) to the before last Microfit pin.
- Short the unused cell connections: 
  - on the PCB using the exposed pads as per the schematic below in cyan
  - or in the wiring harness directly. 

```

2024-06-12 09:32 UTC, jalinei commented
[09bfa76] I've added this minor change to the PR.
It simplifies the user experience when looking how to flash the newest firmware.

2024-06-12 10:24 UTC, martinjaeger approved these changes

2024-06-12 10:27 UTC, merged